stages:
  prepare_data:
    cmd: python src/stage01_prepare.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage01_prepare.py
      - data/data.xml
      - src/utils/common_utils.py
      - src/utils/data_management.py
      - configs/config.yaml
      - params.yaml
    params:
      - prepare.seed
      - prepare.split
    
    outs:
      - artifacts/prepared_data/train.tsv
      - artifacts/prepared_data/test.tsv

  featurize:
    cmd: python src/stage02_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage02_featurization.py
      - artifacts/prepared_data/train.tsv
      - artifacts/prepared_data/test.tsv
      - src/utils/common_utils.py
      - src/utils/featurize.py
      - configs/config.yaml

    params:
      - featurize.max_features
      - featurize.ngrams
    
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl

  train:
    cmd: python src/stage03_train.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage03_train.py
      - artifacts/features/train.pkl
      - src/utils/common_utils.py
      - configs/config.yaml
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - artifacts/model/model.pkl
     
    


    

