artifacts:
    ARTIFACTS_DIR: artifacts
    PREPARED_DATA: prepared_data
    TRAIN_DATA: train.tsv
    TEST_DATA: test.tsv
    FEATURIZED_DATA:  features
    FEATURIZED_OUT_TRAIN: train.pkl
    FEATURISED_OUT_TEST:  test.pkl
    MODEL_DIR: model
    MODEL_NAME: model.pkl


metrics:
    SCORES: scores.json

plots:
    PRC: prc.json
    ROC: roc.json


data_source:
     data_dir: data
     data_file: data.xml