name: nlp-dvc-usecase

on: [push]

jobs:
 run:
   runs-on: [ubuntu-latest]
   steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
         python_version: '3.7'

      - name: cml-run
        env:
           REPO-TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # your ML workflow commands
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro -v

          echo '# REPORTS ' >> reports.md
          echo '## Metrics ' >> reports.md
          cat scores.json  >> reports.md
          
          cml-send-comment report.md
