name: dvc-nlp-workflow-pipeline

on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: deploy runner on EC2
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.DVC_NLP_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml runner \
          --cloud=aws \
          --cloud-region=us-east \
          --cloud-type=t2.micro\
          --labels=cml-cpu
   
  model-training:
    needs: deploy-runner
    runs-on: [self-hosted, cml-cpu]
    container: 
      image: docker://iterativeai/cml:0-dvc2-base1-cpu
    steps:
      - uses: actions/checkout@v2
      - name: "Train my model"
        env:
          REPO_TOKEN: ${{ secrets.DVC_NLP_TOKEN }}
        run: |
          # Your ML workflow commands
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro -v
          
          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md
          cml-send-comment report.md 