name: dvc-nlp-workflow

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
        with: 
          python_version: '3.7'
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # your ML workflow commands
          pip install --upgrade pip
          pip install -r requirements.txt
       
          echo '# REPORTS' >> report.md
          echo '## metrics' >> report.md
          cat artifacts/report/scores.json >> report.md
          
          cml send-comment report.md
