name: dvc-nlp-workflow-pipeline

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v2
        with:
          python-version: "3.7"

      - name: "Run dvc-nlp-workflow-pipeline"
        env:
          REPO_TOKEN: "${{  secrets.GITHUB_TOKEN  }}"
        run: |
          # ML workflow commands here:
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro -v

          echo '# REPORTS ' >> report.md
          echo '## metrics ' >> report.md
          cat scores.json >> report.md

          cml send-comment report.md